#ifndef COMMON_H
#define COMMON_H

/* 
   Standard input-output library 
   Used for printf(), scanf() etc.
*/
#include <stdio.h>

/*
   Standard library
   Used for functions like malloc(), atoi(), rand()
*/
#include <stdlib.h>

/*
   UNIX standard functions
   Used for sleep(), fork(), pipe(), write(), read()
*/
#include <unistd.h>

/*
   String manipulation functions
   Used for strcpy(), strcmp(), sprintf()
*/
#include <string.h>

/*
   POSIX thread library
   Used for pthread_create(), pthread_mutex_lock(), etc.
*/
#include <pthread.h>

/*
   IPC related libraries
   Used for shared memory, semaphore, and message queue
*/
#include <sys/ipc.h>
#include <sys/shm.h>
#include <sys/sem.h>
#include <sys/msg.h>

/*
   System data types
*/
#include <sys/types.h>

/*
   File related system calls
   Used for mkfifo(), open(), close()
*/
#include <sys/stat.h>
#include <fcntl.h>

/*
   Signal handling functions
   Used for signal(), sigaction(), kill()
*/
#include <signal.h>

/*
   Time functions
   Used for srand(), time()
*/
#include <time.h>


/*
   Maximum number of satellites in the simulation
*/
#define MAX_SAT 2


/*
   Name of FIFO (named pipe) used for communication
   between Mission Commander and Data Recorder
*/
#define FIFO_NAME "mission_fifo"


/*
   Keys used for IPC mechanisms
   These keys identify IPC resources in the system
*/
#define SHM_KEY 1234     // shared memory key
#define SEM_KEY 5678     // semaphore key
#define MSG_KEY 9101     // message queue key


/*
   Structure representing telemetry data
   generated by each satellite
*/
typedef struct {

    int sat_id;         // ID of the satellite

    float temperature;  // temperature sensor value

    float battery;      // remaining battery percentage

    float pos_x;        // satellite position X coordinate

    float pos_y;        // satellite position Y coordinate

} telemetry_t;


/*
   Structure stored in shared memory
   It contains telemetry of all satellites
*/
typedef struct {

    telemetry_t satellites[MAX_SAT];

} mission_state_t;


/*
   Structure used for message queue communication
   to send alerts (like low battery)
*/
typedef struct {

    long msg_type;         // message type (required by message queue)

    char msg_text[100];    // alert message text

} alert_msg_t;


/*
   Union required for semaphore control operations
   Used with semctl()
*/
union semun {

    int val;                  // value for SETVAL

    struct semid_ds *buf;     // buffer for IPC_STAT

    unsigned short *array;    // array for GETALL / SETALL

};

#endif
